database:
  host: 127.0.0.1
  name: customer_db
  sql:
    user: local
    password: local_password
    port: 3306
    conn_time: 8000
    max_idle_conns: 10
    max_open_conns: 100
server:
  port: 8080
  trusted_proxies: 
    - "127.0.0.1"
  max_connection_retries: 5
  connection_backoff: 2
  logger:
    gorm:
      slow_sql_speed: 2 