version: '3.8'

services:
  customer_db-master:
    image: mysql:latest
    container_name:  customer_db-master
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: local
      MYSQL_PASSWORD: local_password
      MYSQL_DATABASE: customer_db
      MYSQL_ROOT_PASSWORD: CHANGEME
    volumes:
      - customer_db-master-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  customer_db-master-data: