info:
  contact: {}
paths:
  /customer/:
    post:
      description: Get user by ID
      operationId: post-customer
      parameters:
      - description: Customer ID
        in: body
        name: customerid
        required: true
        schema:
          type: integer
      - description: User Agent
        in: header
        name: useragent
        required: true
        type: string
      - description: Remote IP
        in: body
        name: remoteip
        required: true
        schema:
          type: string
      - description: Timestamp
        in: body
        name: timestamp
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Server Error
      summary: Create User Entry
  /statistics/:
    post:
      description: Get statistics based on Day and customer
      operationId: get-stats
      parameters:
      - description: Customer ID
        in: query
        name: customerid
        required: true
        type: integer
      - description: Day
        in: query
        name: day
        required: true
        type: string
      - description: Timestamp
        in: body
        name: timestamp
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Customer data not found
        "500":
          description: Server Error
      summary: Get statistics based on day and customer
swagger: "2.0"
